### GET
GET http://localhost:3000/shopping-list-item


### GET BY ID
GET http://localhost:3000/shopping-list-item/E7k8CG24Z9smVFAfyYEd

### POST
POST http://localhost:3000/shopping-list-item
Content-Type: application/json

{
  "name": "Chocolate em pó 200g",
  "quantity": 1,
  "user": "Vyctor",
  "createdAt": "2025-01-01",
  "isPurchased": false,
  "isDeleted": false
}

### PUT
PUT http://localhost:3000/shopping-list-item/E7k8CG24Z9smVFAfyYEd
Content-Type: application/json

{
  "name": "Chocolate em pó 200g",
  "quantity": 1,
  "user": "Vyctor",
  "createdAt": "2025-01-01",
  "isPurchased": false
}


### DELETE
DELETE http://localhost:3000/shopping-list-item/E7k8CG24Z9smVFAfyYEd